language: node_js
node_js:
  - "0.10"
before_install:
  - rvm use 1.9.3
install:
  - npm install -g grunt-cli
  - npm install
  - gem install --no-document "jekyll:1.4.2" "sass:3.2.15"
matrix:
  fast_finish: true
