# Meta data
name:         General
authors:      Jack cai
description:  A General Simple Web front-end framework with HTML 、CSS and JS Componments

# Dependencies
pygments:     true

# Permalinks
permalink:    pretty

# Server
source:       docs
port:         4000
url:          http://web.caibaojian.com